#!/usr/bin/env python

#
# Search for information in programming documentation
#

import os, sys
MAX_RESULTS = 15

# Must provide at least a search string
if len(sys.argv) < 2:
    print """No query specified!
Usage: doc [lang] query
"""
    exit(1)
else:
    if len(sys.argv) == 2:
        search_path = ''
        search_string = sys.argv[1]
    else:
        search_path = '/' + sys.argv[1]
        search_string = sys.argv[2]
search_path = '/DevDocs' + search_path

stdout = os.popen('mdfind -onlyin ~/Documents' + search_path + ' ' + search_string)
text = stdout.read()
files = text.split("\n")

for num in range(MAX_RESULTS):
    print str(num + 1) + '  ' + files[num][files[num].index(search_path + '/') + len(search_path) + 1:]

# Get input for file to open
open_num = raw_input('Which file would you like to open? ')
while (not open_num.isdigit()) or not (int(open_num) > 0 and int(open_num) <= MAX_RESULTS):
    open_num = raw_input('Try again, jackass: ')

# open the file
open_num = int(open_num)
os.system('open ' + files[open_num])