#!/bin/bash
# -------------------------------------------------------------
# vlog N
# List (verbosely) the last N commits to SVN repo.
# -------------------------------------------------------------

svn log -v --limit $1

